services:
  - type: web
    name: prism-agency
    env: node
    buildCommand: npm install
    startCommand: node server/server.js
    plan: free
    envVars:
      - key: NODE_ENV
        value: production
      - key: EMAIL_HOST
        value: smtp.gmail.com
      - key: EMAIL_PORT
        value: "587"
      - key: EMAIL_USER
        sync: false
      - key: EMAIL_PASS
        sync: false
      - key: EMAIL_FROM
        sync: false
      - key: EMAIL_TO
        sync: false
